In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/전력+사용량(용도별).csv', encoding='utf-8')

In [4]:
df.columns

Index(['자치구별(1)', '자치구별(2)', '2004', '2004.1', '2004.2', '2004.3', '2004.4',
       '2004.5', '2004.6', '2004.7',
       ...
       '2022.2', '2022.3', '2022.4', '2022.5', '2022.6', '2022.7', '2022.8',
       '2022.9', '2022.10', '2022.11'],
      dtype='object', length=230)

In [14]:
selected_columns = df[['자치구별(2)', '2022']]

In [15]:
selected_columns

    자치구별(2)      2022
0   자치구별(2)        합계
1   자치구별(2)        소계
2   자치구별(2)        소계
3        소계  48788677
4       종로구   1721240
5        중구   2305200
6       용산구   1514990
7       성동구   2235050
8       광진구   1616001
9      동대문구   1457689
10      중랑구   1161372
11      성북구   1497475
12      강북구    933057
13      도봉구    894641
14      노원구   1540077
15      은평구   1505392
16     서대문구   1297535
17      마포구   2265953
18      양천구   1797687
19      강서구   2752727
20      구로구   1927165
21      금천구   1691616
22     영등포구   2782101
23      동작구   1298388
24      관악구   1735924
25      서초구   3291898
26      강남구   4822166
27      송파구   3084332
28      강동구   1659003

In [16]:
selected_columns_filtered = selected_columns.drop(index=range(4))

In [18]:
selected_columns_filtered.columns = ['자치구명', '전력사용량']

In [19]:
selected_columns_filtered.head()

  자치구명    전력사용량
4  종로구  1721240
5   중구  2305200
6  용산구  1514990
7  성동구  2235050
8  광진구  1616001